module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOG_OUT: "LOG_OUT",
  PRIVATE_CHAT: "PRIVATE_CHAT",
  FILE_SENT: "FILE_SENT",
  FILE_RECEIVED: "FILE_RECEIVED",
};